# Generated by Django 4.2.7 on 2023-12-10 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_contribution', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=70, null=True)),
                ('bank_account', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=70, null=True)),
                ('total_contribution', models.PositiveIntegerField(default=0)),
                ('total_loan', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
