# Generated by Django 4.2.7 on 2023-12-10 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('price', models.PositiveIntegerField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrowed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('is_tresurer_approved', models.BooleanField(default=False)),
                ('is_president_approved', models.BooleanField(default=False)),
                ('is_tresurer_declined', models.BooleanField(default=False)),
                ('is_president_declined', models.BooleanField(default=False)),
                ('is_user_declined', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('date_declined', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('comments', models.ManyToManyField(blank=True, to='loans.comment')),
            ],
            options={
                'ordering': ('-date_initiated',),
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorHomeAppliances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAwaitingDisbursmentQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan', models.ManyToManyField(blank=True, to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApprovalQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan', models.ManyToManyField(blank=True, related_name='approvalqueue', to='loans.loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loantype'),
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan', to='members.member'),
        ),
        migrations.CreateModel(
            name='HomeAppliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('price', models.PositiveIntegerField()),
                ('starting_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.vendorhomeappliances')),
            ],
        ),
    ]
