# Generated by Django 4.2.7 on 2023-12-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loantype_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='is_tresurer_approved',
            new_name='is_treasurer_approved',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='is_tresurer_declined',
            new_name='is_treasurer_declined',
        ),
    ]
