# Generated by Django 4.2.7 on 2023-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_rename_comment_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
