# Generated by Django 4.2.7 on 2023-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_comment_date_commented'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_commented',)},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='attachments',
        ),
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
