# Generated by Django 4.2.7 on 2023-12-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_comment_options_remove_loan_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
