# Generated by Django 4.2.7 on 2023-12-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_comment_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_repaid',
            field=models.BooleanField(default=False),
        ),
    ]
